# Generated by Django 5.0.6 on 2024-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=640)),
                ('picture_url', models.CharField(max_length=240)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
