# Generated by Django 5.0.6 on 2024-05-30 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_categories_category_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageUrl',
            new_name='imageURL',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
